services:
  harvey-nginx:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'host.docker.internal:5000/health']
      interval: 10s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.http.routers.harveyapi.rule=Host(`harveyapi.justinpaulhammond.com`, `www.harveyapi.justinpaulhammond.com`)"
      - "traefik.http.routers.harveyapi.tls=true"
      - "traefik.http.routers.harveyapi.tls.certresolver=letsencrypt"
