services:
  harvey:
    deploy:
      replicas: 2
    mem_limit: '1024m'
    healthcheck:
      test: ['CMD-SHELL', 'if [ ! -e /var/run/nginx.pid ]; then exit 1; else exit 0; fi']
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /Users/admin/harvey:/data
