services:
  harvey-nginx:
    build: .
    restart: always
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - 'traefik.docker.network=traefik'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  traefik:
    name: traefik
    external: true
