services:
  harvey:
    build: .
    restart: always
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /Users/jhammond/harvey:/lala
      - ./:/app

networks:
  traefik:
    name: traefik
    external: true
